In [1]:
import pandas as pd
import numpy as np

In [2]:
songs = pd.read_csv("dataset (1).csv")

songs.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [3]:
songs = songs[
[
'track_name',
'artists',
'track_genre',
'popularity'
]
]

In [4]:
songs.columns = [
'song',
'artist',
'genre',
'popularity'
]

In [5]:
songs = songs.drop_duplicates(
subset=['song','artist']
)

In [7]:
lyrics = pd.read_csv(
"spotify_millsongdata.csv"
)

lyrics.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [8]:
lyrics = lyrics[
[
'song',
'artist',
'text'
]
]

In [9]:
lyrics.rename(
columns={
'text':'lyrics'
},
inplace=True
)

In [10]:
lyrics['lyrics'] = (
lyrics['lyrics']
.astype(str)
.str.replace('\r',' ')
.str.replace('\n',' ')
)

In [11]:
songs['song'] = (
songs['song']
.astype(str)
.str.lower()
)

songs['artist'] = (
songs['artist']
.astype(str)
.str.lower()
)

lyrics['song'] = (
lyrics['song']
.astype(str)
.str.lower()
)

lyrics['artist'] = (
lyrics['artist']
.astype(str)
.str.lower()
)

In [12]:
zuno = pd.merge(
songs,
lyrics,
on=['song','artist'],
how='inner'
)

In [13]:
print(zuno.shape)

zuno.head()

(1360, 5)

,song,artist,genre,popularity,lyrics
0,i'm yours,jason mraz,acoustic,80,Well you done done me and you bet I felt it ...
1,i won't give up,jason mraz,acoustic,69,When I look into your eyes It's like watchi...
2,93 million miles,jason mraz,acoustic,0,93 million miles from the sun People get re...
3,bella luna,jason mraz,acoustic,1,Mystery the moon A hole in the sky A sup...
4,winter wonderland,jason mraz,acoustic,0,"Sleigh bells ring, are you listening, In th..."

In [14]:
zuno.to_csv(
"zuno_dataset.csv",
index=False
)