In [2]:
pip install transformers sentencepiece torch

Requirement already satisfied: transformers in c:\users\amrit\downloads\anaconda\lib\site-packages (5.10.2)
Requirement already satisfied: sentencepiece in c:\users\amrit\downloads\anaconda\lib\site-packages (0.2.1)
Requirement already satisfied: torch in c:\users\amrit\downloads\anaconda\lib\site-packages (2.12.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from transformers) (1.18.0)
Requirement already satisfied: numpy>=1.17 in c:\users\amrit\downloads\anaconda\lib\site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\amrit\downloads\anaconda\lib\site-packages (from transformers) (6.0.1)
Requirement already satisfied: regex>=2025.10.22 in c:\users\amrit\downloads\anaconda\lib\site-packages (from transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\amrit\downloads\anaconda\lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\amrit\downloads\anaconda\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\amrit\downloads\anaconda\lib\site-packages (from transformers) (4.66.5)
Requirement already satisfied: filelock in c:\users\amrit\downloads\anaconda\lib\site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from torch) (4.14.0)
Requirement already satisfied: setuptools<82 in c:\users\amrit\downloads\anaconda\lib\site-packages (from torch) (75.1.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\amrit\downloads\anaconda\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\amrit\downloads\anaconda\lib\site-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in c:\users\amrit\downloads\anaconda\lib\site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\amrit\downloads\anaconda\lib\site-packages (from torch) (2024.6.1)
Requirement already satisfied: click>=8.4.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\amrit\downloads\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.27.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\users\amrit\downloads\anaconda\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\amrit\downloads\anaconda\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: anyio in c:\users\amrit\downloads\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.2.0)
Requirement already satisfied: certifi in c:\users\amrit\downloads\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2024.8.30)
Requirement already satisfied: httpcore==1.* in c:\users\amrit\downloads\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.2)
Requirement already satisfied: idna in c:\users\amrit\downloads\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.7)
Requirement already satisfied: sniffio in c:\users\amrit\downloads\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\amrit\downloads\anaconda\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.14.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\amrit\downloads\anaconda\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install google-generativeai

Note: you may need to restart the kernel to use updated packages.Collecting google-generativeai
  Downloading google_generativeai-0.8.6-py3-none-any.whl.metadata (3.9 kB)
Collecting google-ai-generativelanguage==0.6.15 (from google-generativeai)
  Downloading google_ai_generativelanguage-0.6.15-py3-none-any.whl.metadata (5.7 kB)
Collecting google-api-core (from google-generativeai)
  Downloading google_api_core-2.31.0-py3-none-any.whl.metadata (3.2 kB)
Collecting google-api-python-client (from google-generativeai)
  Downloading google_api_python_client-2.197.0-py3-none-any.whl.metadata (7.0 kB)
Collecting google-auth>=2.15.0 (from google-generativeai)
  Downloading google_auth-2.53.0-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: protobuf in c:\users\amrit\downloads\anaconda\lib\site-packages (from google-generativeai) (4.25.3)
Requirement already satisfied: pydantic in c:\users\amrit\downloads\anaconda\lib\site-packages (from google-generativeai) (2.8.2)
Requirement already satisfied: tqdm in c:\users\amrit\downloads\anaconda\lib\site-packages (from google-generativeai) (4.66.5)
Requirement already satisfied: typing-extensions in c:\users\amrit\downloads\anaconda\lib\site-packages (from google-generativeai) (4.14.0)
Collecting proto-plus<2.0.0dev,>=1.22.3 (from google-ai-generativelanguage==0.6.15->google-generativeai)
  Downloading proto_plus-1.28.0-py3-none-any.whl.metadata (2.2 kB)
Collecting googleapis-common-protos<2.0.0,>=1.63.2 (from google-api-core->google-generativeai)
  Downloading googleapis_common_protos-1.75.0-py3-none-any.whl.metadata (8.6 kB)
Collecting protobuf (from google-generativeai)
  Downloading protobuf-5.29.6-cp310-abi3-win_amd64.whl.metadata (592 bytes)
Collecting requests<3.0.0,>=2.33.0 (from google-api-core->google-generativeai)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\amrit\downloads\anaconda\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (0.2.8)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\amrit\downloads\anaconda\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (43.0.0)
Collecting httplib2<1.0.0,>=0.19.0 (from google-api-python-client->google-generativeai)
  Downloading httplib2-0.31.2-py3-none-any.whl.metadata (2.2 kB)
Collecting google-auth-httplib2<1.0.0,>=0.2.0 (from google-api-python-client->google-generativeai)
  Downloading google_auth_httplib2-0.4.0-py3-none-any.whl.metadata (3.0 kB)
Collecting uritemplate<5,>=3.0.1 (from google-api-python-client->google-generativeai)
  Downloading uritemplate-4.2.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from pydantic->google-generativeai) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\amrit\downloads\anaconda\lib\site-packages (from pydantic->google-generativeai) (2.20.1)
Requirement already satisfied: colorama in c:\users\amrit\downloads\anaconda\lib\site-packages (from tqdm->google-generativeai) (0.4.6)
Requirement already satisfied: cffi>=1.12 in c:\users\amrit\downloads\anaconda\lib\site-packages (from cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (1.17.1)
Collecting grpcio<2.0.0,>=1.41.0 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai)
  Downloading grpcio-1.81.0-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Collecting grpcio-status<2.0.0,>=1.41.0 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai)
  Downloading grpcio_status-1.81.0-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: pyparsing<4,>=3.1 in c:\users\amrit\downloads\anaconda\lib\site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.1.2)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\amrit\downloads\anaconda\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.4.8)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\amrit\downloads\anaconda\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core->google-generativeai) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\amrit\downloads\anaconda\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core->google-generativeai) (3.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\amrit\downloads\anaconda\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core->google-generativeai) (2.2.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\amrit\downloads\anaconda\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core->google-generativeai) (2024.8.30)
Requirement already satisfied: pycparser in c:\users\amrit\downloads\anaconda\lib\site-packages (from cffi>=1.12->cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (2.21)
INFO: pip is looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.
  Downloading grpcio_status-1.80.0-py3-none-any.whl.metadata (1.3 kB)
  Downloading grpcio_status-1.78.0-py3-none-any.whl.metadata (1.3 kB)
  Downloading grpcio_status-1.76.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.75.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.75.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.74.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.73.1-py3-none-any.whl.metadata (1.1 kB)
INFO: pip is still looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.
  Downloading grpcio_status-1.73.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.72.2-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.72.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.71.2-py3-none-any.whl.metadata (1.1 kB)
Downloading google_generativeai-0.8.6-py3-none-any.whl (155 kB)
Downloading google_ai_generativelanguage-0.6.15-py3-none-any.whl (1.3 MB)
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   --------------- ------------------------ 0.5/1.3 MB 75.9 kB/s eta 0:00:11
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ----------------------- ---------------- 0.8/1.3 MB 59.5 kB/s eta 0:00:10
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ------------------------------- -------- 1.0/1.3 MB 60.1 kB/s eta 0:00:05
   ---------------------------------------- 1.3/1.3 MB 59.6 kB/s eta 0:00:00
Downloading google_api_core-2.31.0-py3-none-any.whl (173 kB)
Downloading google_auth-2.53.0-py3-none-any.whl (246 kB)
Downloading protobuf-5.29.6-cp310-abi3-win_amd64.whl (435 kB)
Downloading google_api_python_client-2.197.0-py3-none-any.whl (15.3 MB)
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.3 MB ? eta -:--:--
    --------------------------------------- 0.3/15.3 MB ? eta -:--:--
    --------------------------------------- 0.3/15.3 MB ? eta -:--:--
    --------------------------------------- 0.3/15.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/15.3 MB 409.6 kB/s eta 0:00:37
   -- ------------------------------------- 0.8/15.3 MB 524.3 kB/s eta 0:00:28
   -- ------------------------------------- 1.0/15.3 MB 621.7 kB/s eta 0:00:23
   -- ------------------------------------- 1.0/15.3 MB 621.7 kB/s eta 0:00:23
   --- ------------------------------------ 1.3/15.3 MB 639.4 kB/s eta 0:00:22
   --- ------------------------------------ 1.3/15.3 MB 639.4 kB/s eta 0:00:22
   --- ------------------------------------ 1.3/15.3 MB 639.4 kB/s eta 0:00:22
   ---- ----------------------------------- 1.6/15.3 MB 586.7 kB/s eta 0:00:24
   ---- ----------------------------------- 1.6/15.3 MB 586.7 kB/s eta 0:00:24
   ---- ----------------------------------- 1.6/15.3 MB 586.7 kB/s eta 0:00:24
   ---- ----------------------------------- 1.6/15.3 MB 586.7 kB/s eta 0:00:24
   ---- ----------------------------------- 1.6/15.3 MB 586.7 kB/s eta 0:00:24
   ---- ----------------------------------- 1.8/15.3 MB 470.5 kB/s eta 0:00:29
   ---- ----------------------------------- 1.8/15.3 MB 470.5 kB/s eta 0:00:29
   ---- ----------------------------------- 1.8/15.3 MB 470.5 kB/s eta 0:00:29
   ---- ----------------------------------- 1.8/15.3 MB 470.5 kB/s eta 0:00:29
   ---- ----------------------------------- 1.8/15.3 MB 470.5 kB/s eta 0:00:29
   ----- ---------------------------------- 2.1/15.3 MB 410.7 kB/s eta 0:00:33
   ----- ---------------------------------- 2.1/15.3 MB 410.7 kB/s eta 0:00:33
   ----- ---------------------------------- 2.1/15.3 MB 410.7 kB/s eta 0:00:33
   ----- ---------------------------------- 2.1/15.3 MB 410.7 kB/s eta 0:00:33
   ----- ---------------------------------- 2.1/15.3 MB 410.7 kB/s eta 0:00:33
   ----- ---------------------------------- 2.1/15.3 MB 410.7 kB/s eta 0:00:33
   ----- ---------------------------------- 2.1/15.3 MB 410.7 kB/s eta 0:00:33
   ----- ---------------------------------- 2.1/15.3 MB 410.7 kB/s eta 0:00:33
   ----- ---------------------------------- 2.1/15.3 MB 410.7 kB/s eta 0:00:33
   ----- ---------------------------------- 2.1/15.3 MB 410.7 kB/s eta 0:00:33
   ------ --------------------------------- 2.4/15.3 MB 324.2 kB/s eta 0:00:40
   ------ --------------------------------- 2.4/15.3 MB 324.2 kB/s eta 0:00:40
   ------ --------------------------------- 2.4/15.3 MB 324.2 kB/s eta 0:00:40
   ------ --------------------------------- 2.4/15.3 MB 324.2 kB/s eta 0:00:40
   ------ --------------------------------- 2.4/15.3 MB 324.2 kB/s eta 0:00:40
   ------ --------------------------------- 2.4/15.3 MB 324.2 kB/s eta 0:00:40
   ------ --------------------------------- 2.4/15.3 MB 324.2 kB/s eta 0:00:40
   ------ --------------------------------- 2.4/15.3 MB 324.2 kB/s eta 0:00:40
   ------ --------------------------------- 2.4/15.3 MB 324.2 kB/s eta 0:00:40
   ------ --------------------------------- 2.4/15.3 MB 324.2 kB/s eta 0:00:40
   ------ --------------------------------- 2.4/15.3 MB 324.2 kB/s eta 0:00:40
   ------ --------------------------------- 2.4/15.3 MB 324.2 kB/s eta 0:00:40
   ------ --------------------------------- 2.4/15.3 MB 324.2 kB/s eta 0:00:40
   ------ --------------------------------- 2.4/15.3 MB 324.2 kB/s eta 0:00:40
   ------ --------------------------------- 2.6/15.3 MB 246.7 kB/s eta 0:00:52
   ------ --------------------------------- 2.6/15.3 MB 246.7 kB/s eta 0:00:52
   ------ --------------------------------- 2.6/15.3 MB 246.7 kB/s eta 0:00:52
   ------ --------------------------------- 2.6/15.3 MB 246.7 kB/s eta 0:00:52
   ------ --------------------------------- 2.6/15.3 MB 246.7 kB/s eta 0:00:52
   ------ --------------------------------- 2.6/15.3 MB 246.7 kB/s eta 0:00:52
   ------ --------------------------------- 2.6/15.3 MB 246.7 kB/s eta 0:00:52

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas-profiling 3.2.0 requires joblib~=1.1.0, but you have joblib 1.5.2 which is incompatible.
pandas-profiling 3.2.0 requires visions[type_image_path]==0.7.4, but you have visions 0.8.1 which is incompatible.
streamlit 1.37.1 requires rich<14,>=10.14.0, but you have rich 15.0.0 which is incompatible.

In [19]:
import pandas as pd
import google.generativeai as genai

In [18]:
import google.generativeai as genai

genai.configure(
    api_key="AQ.Ab8RN6KCKEn6VQo9SetVk1RrcVI7rm05XQoAmgK_baYqqJApPw"
)

model = genai.GenerativeModel(
    "gemini-2.5-flash"
)

response = model.generate_content(
    "Say hello"
)

print(response.text)

C:\Users\amrit\AppData\Local\Temp\ipykernel_31204\4047456366.py:1: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  import google.generativeai as genai

Hello!

In [5]:
import pandas as pd
df = pd.read_csv(
    "zuno_dataset.csv"
)

df.head()

,song,artist,genre,popularity,lyrics
0,i'm yours,jason mraz,acoustic,80,Well you done done me and you bet I felt it ...
1,i won't give up,jason mraz,acoustic,69,When I look into your eyes It's like watchi...
2,93 million miles,jason mraz,acoustic,0,93 million miles from the sun People get re...
3,bella luna,jason mraz,acoustic,1,Mystery the moon A hole in the sky A sup...
4,winter wonderland,jason mraz,acoustic,0,"Sleigh bells ring, are you listening, In th..."

In [6]:
def translate_lyrics(lyrics):

    lyrics = str(lyrics)

    lyrics = lyrics[:500]

    prompt = f"""
    Translate the following lyrics into English.

    Only return the translated lyrics.

    Lyrics:
    {lyrics}
    """

    response = model.generate_content(
        prompt
    )

    return response.text

In [7]:
def get_song(song_name):

    result = df[
        df['song']
        .str.lower()
        ==
        song_name.lower()
    ]

    return result

In [8]:
song_name = input(
    "Enter Song Name: "
)

Enter Song Name:  i'm yours

In [9]:
song_data = get_song(
    song_name
)

song_data

,song,artist,genre,popularity,lyrics
0,i'm yours,jason mraz,acoustic,80,Well you done done me and you bet I felt it ...

In [10]:
lyrics = song_data[
    'lyrics'
].values[0]

print(
    lyrics[:1000]
)

Well you done done me and you bet I felt it    I tried to be chill but you're so hot that I melted    I fell right through the cracks    And now I'm trying to get back    Before the cool done run out    I'll be giving it my bestest    And nothing's going to stop me but divine intervention    I reckon it's again my turn,    To win some or learn some        But I won't hesitate no more, no more    It cannot wait, I'm yours        Well open up your mind and see like me    Open up your plans and damn you're free    Look into your heart and you'll find love love love love    Listen to the music of the moment people dance and sing    We are just one big family    And It's our God-forsaken right to be loved loved loved loved loved        [Chorus]    So I won't hesitate no more, no more    It cannot wait I'm sure    There's no need to complicate    Our time is short    This is our fate, I'm yours        I've been spending way too long checking my tongue in the mirror    And bending over backwa

In [11]:
print(song_name)

i'm yours

In [12]:
df[
    df['song']
    .str.contains(
        "despacito",
        case=False,
        na=False
    )
]

Empty DataFrame
Columns: [song, artist, genre, popularity, lyrics]
Index: []

In [13]:
df['song'].sample(20)

740                           st. anger
1138                  love conquers all
206                    someone like you
1195                        radioactive
265          like we never loved at all
754                            you lied
545                     hands held high
207                  when we were young
1317                 no one is to blame
868               great big white world
864              right where it belongs
1090                  a pillow of winds
24                        turn to stone
188                     make it wit chu
398              brown girl in the ring
1035                          hash pipe
537                               breed
472                in the midnight hour
447     getting ready for christmas day
184            i can't make you love me
Name: song, dtype: object

In [14]:
songs = pd.read_csv("dataset (1).csv")

lyrics = pd.read_csv("spotify_millsongdata.csv")

print("Songs Dataset:", songs.shape)

print("Lyrics Dataset:", lyrics.shape)

print("Merged Dataset:", df.shape)

Songs Dataset: (114000, 21)
Lyrics Dataset: (57650, 4)
Merged Dataset: (1360, 5)

In [15]:
song_name = "all i ask"
sample_song = df.iloc[0]['song']

print("Selected Song:")
print(sample_song)
song_data = df[
    df['song'] == sample_song
]

song_data.head()

Selected Song:
i'm yours

,song,artist,genre,popularity,lyrics
0,i'm yours,jason mraz,acoustic,80,Well you done done me and you bet I felt it ...

In [16]:
lyrics = song_data[
    'lyrics'
].values[0]

print(
    lyrics[:1000]
)

Well you done done me and you bet I felt it    I tried to be chill but you're so hot that I melted    I fell right through the cracks    And now I'm trying to get back    Before the cool done run out    I'll be giving it my bestest    And nothing's going to stop me but divine intervention    I reckon it's again my turn,    To win some or learn some        But I won't hesitate no more, no more    It cannot wait, I'm yours        Well open up your mind and see like me    Open up your plans and damn you're free    Look into your heart and you'll find love love love love    Listen to the music of the moment people dance and sing    We are just one big family    And It's our God-forsaken right to be loved loved loved loved loved        [Chorus]    So I won't hesitate no more, no more    It cannot wait I'm sure    There's no need to complicate    Our time is short    This is our fate, I'm yours        I've been spending way too long checking my tongue in the mirror    And bending over backwa

In [20]:
translation = translate_lyrics(
    lyrics
)

print(translation)

Well you done done me and you bet I felt it
I tried to be chill but you're so hot that I melted
I fell right through the cracks
And now I'm trying to get back
Before the cool done run out
I'll be giving it my bestest
And nothing's going to stop me but divine intervention
I reckon it's again my turn,
To win some or learn some

But I won't hesitate no more, no more
It cannot wait, I'm yours

Well open up your mind and see like me
Open up your plans and dam

In [21]:
def translate_song(song_name):

    song_data = df[
        df['song']
        .str.lower()
        ==
        song_name.lower()
    ]

    if len(song_data) == 0:

        print("Song Not Found")

        return None

    lyrics = song_data[
        'lyrics'
    ].values[0]

    translation = translate_lyrics(
        lyrics
    )

    return translation

In [22]:
translate_song(
    sample_song
)

"Well you done done me and you bet I felt it    I tried to be chill but you're so hot that I melted    I fell right through the cracks    And now I'm trying to get back    Before the cool done run out    I'll be giving it my bestest    And nothing's going to stop me but divine intervention    I reckon it's again my turn,    To win some or learn some        But I won't hesitate no more, no more    It cannot wait, I'm yours        Well open up your mind and see like me    Open up your plans and dam"

In [23]:
song_name = input(
    "Enter Song Name: "
)

result = translate_song(
    song_name
)

print(result)

Enter Song Name:  i'm yours

Well you done done me and you bet I felt it
I tried to be chill but you're so hot that I melted
I fell right through the cracks
And now I'm trying to get back
Before the cool done run out
I'll be giving it my bestest
And nothing's going to stop me but divine intervention
I reckon it's again my turn,
To win some or learn some

But I won't hesitate no more, no more
It cannot wait, I'm yours

Well open up your mind and see like me
Open up your plans and dam

In [24]:
song_name = df.iloc[0]['song']

translate_song(song_name)

"Well you done done me and you bet I felt it I tried to be chill but you're so hot that I melted I fell right through the cracks And now I'm trying to get back Before the cool done run out I'll be giving it my bestest And nothing's going to stop me but divine intervention I reckon it's again my turn, To win some or learn some But I won't hesitate no more, no more It cannot wait, I'm yours Well open up your mind and see like me Open up your plans and dam"

In [26]:
import json
translation_cache = {}
with open(
    "translations.json",
    "w"
) as f:

    json.dump(
        translation_cache,
        f,
        indent=4
    )